FROM python:3.12-slim
WORKDIR /worker
RUN apt-get update && apt-get install -y --no-install-recommends libreoffice-writer fonts-thai-tlwg && rm -rf /var/lib/apt/lists/*
COPY soc-worker/requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
COPY soc-worker/ ./
CMD ["python", "worker.py"]
